export const sampleRequests = [
  {
    id: "req-101",
    title: "Add exportable customer feedback digest",
    description:
      "Customer success wants a weekly digest they can share with account teams without manually copying notes from the product backlog.",
    submitter_name: "Rachel Kim",
    submitter_priority: "Very High",
    reach: 420,
    impact: 2.5,
    confidence: 80,
    effort: 3,
    rice_score: 280,
    notes:
      "Good candidate for an early quarter slot because it helps a cross-functional team and reduces manual reporting work.",
    is_archived: false,
    status: "planned",
    placement: "q2",
    created_at: "2026-04-01",
    updated_at: "2026-04-06",
  },
  {
    id: "req-102",
    title: "Improve onboarding checklist completion visibility",
    description:
      "Sales enablement wants a clearer view into which onboarding steps are skipped most often so they can adjust training materials.",
    submitter_name: "Jordan Lee",
    submitter_priority: "High",
    reach: 250,
    impact: 2,
    confidence: 75,
    effort: 2,
    rice_score: 187.5,
    notes: "",
    is_archived: false,
    status: "scored",
    placement: "unassigned",
    created_at: "2026-04-04",
    updated_at: "2026-04-08",
  },
  {
    id: "req-103",
    title: "Support regional billing contact preferences",
    description:
      "Finance operations needs account-specific billing contacts by region so escalations route faster when invoices fail.",
    submitter_name: "Monica Alvarez",
    submitter_priority: "Medium",
    reach: null,
    impact: null,
    confidence: null,
    effort: null,
    rice_score: null,
    notes: "",
    is_archived: false,
    status: "submitted",
    placement: "unassigned",
    created_at: "2026-04-07",
    updated_at: "2026-04-07",
  },
  {
    id: "req-104",
    title: "Add self-serve roadmap status summaries",
    description:
      "Marketing asked for a shareable summary view so launch partners can track committed roadmap items without asking product each week.",
    submitter_name: "Nina Shah",
    submitter_priority: "Low",
    reach: 160,
    impact: 1.5,
    confidence: 70,
    effort: 2,
    rice_score: 84,
    notes: "Useful but not urgent. Backlog unless a broader roadmap transparency initiative starts.",
    is_archived: false,
    status: "planned",
    placement: "backlog",
    created_at: "2026-03-29",
    updated_at: "2026-04-05",
  },
];
